// <auto-generated />
using LAbb_4_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LAbb_4_API.Migrations
{
    [DbContext(typeof(ProgramDbContext))]
    [Migration("20220316134142_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LAbb_4_API.Models.Interests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("InterestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestDescription = "Padel is a racquet sport that combines the elements of tennis, squash and badminton.",
                            InterestName = "Padel"
                        },
                        new
                        {
                            Id = 2,
                            InterestDescription = "A sport in which participants climb up, down or across natural rock formations or artificial rock walls.",
                            InterestName = "Rock climbing"
                        },
                        new
                        {
                            Id = 3,
                            InterestDescription = "Coding makes it possible for us to create computer software, games, apps and websites.",
                            InterestName = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            InterestDescription = "Surfing is the sport of riding waves in an upright or prone position. Surfers catch the ocean, river, or man-made waves and glide across the surface",
                            InterestName = "Surfing"
                        });
                });

            modelBuilder.Entity("LAbb_4_API.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Viktor",
                            PhoneNumber = "0701234599"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lukas",
                            PhoneNumber = "0704593288"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Erik",
                            PhoneNumber = "0707842511"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Simon",
                            PhoneNumber = "0738432077"
                        });
                });

            modelBuilder.Entity("LAbb_4_API.Models.WebbAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("WebbSiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("webbAdress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("webbAdresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WebbSiteName = "World Padel Tour",
                            webbAdress = "https://www.worldpadeltour.com/en"
                        },
                        new
                        {
                            Id = 2,
                            WebbSiteName = "Climb Europe",
                            webbAdress = "https://climb-europe.com/"
                        },
                        new
                        {
                            Id = 3,
                            WebbSiteName = "Code Cademy",
                            webbAdress = "https://www.codecademy.com/"
                        },
                        new
                        {
                            Id = 4,
                            WebbSiteName = "Surfer Today",
                            webbAdress = "https://www.surfertoday.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
